
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     */
    public kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        total = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        label10 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        Bmenu = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PEMBAYARAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 230, 50);

        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(200, 80, 80, 40);

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(500, 80, 100, 40);

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(290, 80, 90, 40);

        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(390, 80, 100, 40);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Menu", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 130, 600, 280);
        getContentPane().add(label10);
        label10.setBounds(200, 470, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal Pembelian");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 470, 120, 30);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(200, 430, 170, 30);

        Bmenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bmenu.setText("Menu");
        Bmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmenuActionPerformed(evt);
            }
        });
        getContentPane().add(Bmenu);
        Bmenu.setBounds(720, 483, 80, 30);

        refresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(610, 80, 103, 40);

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(720, 80, 80, 40);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(null);

        nomr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomrActionPerformed(evt);
            }
        });
        jPanel1.add(nomr);
        nomr.setBounds(20, 140, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 110, 50, 20);
        jPanel1.add(harga);
        harga.setBounds(20, 370, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 340, 50, 20);
        jPanel1.add(jumlah);
        jumlah.setBounds(20, 290, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 250, 50, 20);

        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(20, 210, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Menu");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 800, 520);

        setBounds(0, 0, 845, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        int jmlBaris = table.getRowCount();
        int totalBiaya = 0;
        int jmlBarang, hargaBarang;
        TableModel tabelModel;
        tabelModel = table.getModel();
        for (int i=0; i<jmlBaris; i++){
        jmlBarang = Integer.parseInt(tabelModel.getValueAt(i, 2).toString());
        hargaBarang = Integer.parseInt(tabelModel.getValueAt(i, 3).toString());
        totalBiaya = totalBiaya + (jmlBarang*hargaBarang);
        }
        if (totalBiaya > 200000) {
            int diskon = totalBiaya*10/100;
            hasil.setText(String.valueOf(totalBiaya-diskon));
        }else
            hasil.setText(String.valueOf(totalBiaya));
        String hasil;
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        table.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if("".equals(menu.getText()) || "".equals(jumlah.getText()) || "".equals(harga.getText())) 
       {
        JOptionPane.showMessageDialog(this,"Harap lengkapi data","Error", JOptionPane.WARNING_MESSAGE);
    }else{
            int hrg = Integer.parseInt(String.valueOf(harga.getText()));
            int jml =Integer.parseInt(String.valueOf(jumlah.getText()));
            int total = hrg*jml;
            
            harga.setText(String.valueOf(total));
        }
        String SQL = "INSERT INTO kasir(menu,jumlah,harga)"+"VALUES ('"+menu.getText()+"','"+harga.getText()+"','"+jumlah.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if(status == 1){
        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES",
                JOptionPane.INFORMATION_MESSAGE);
        selectData();
        } else {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data!","",JOptionPane.YES_NO_OPTION);
        int baris = table.getSelectedRow();
        if (konfirmasi ==0) {
  
        if (baris != -1) {
            String id = table.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM kasir WHERE no='"+nomr.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            
            if (status==1) {    
                JOptionPane.showMessageDialog(this,"Data Berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this,"Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void BmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmenuActionPerformed
            new menu().show();
                this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BmenuActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
 MessageFormat header = new MessageFormat("Pembayaran Restaurant Yuhuuu");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try{
            table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot Print",e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void nomrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bmenu;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private com.toedter.calendar.JDateChooser label10;
    private javax.swing.JTextField menu;
    private javax.swing.JTextField nomr;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
         String kolom[]={"Menu","Harga","Jumlah"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);   
        String SQL = "SELECT * FROM kasir";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String item = rs.getString(1);
                String jumlah = rs.getString(2);
                String harga = rs.getString(3);
                    String data[] = {item,jumlah,harga};
                    dtm.addRow(data);
            }
        }   catch(SQLException ex){
                    Logger.getLogger(kasir.class.getName()).log(Level.SEVERE,null, ex);
                    }
            table.setModel(dtm);
    }
}